### PR TITLE
Add helm chart

### PR DESCRIPTION
**Pull request by cklingspor**
Hey everyone,

I've created a first draft of a helm chart for the parquet-exporter. I do not have a setup where I can use AWS as of now, therefore the actual push to a S3 bucket is not yet tested. However, I was able to install the chart and run the cronjob in my minikube. 

- Used [helm-docs](https://github.com/norwoodj/helm-docs) to  create a rough documentation around the chart
- The chart itself is relatively straight forward I think

Let me know what you think!

### CODE REVIEW

**Comment by mattray** [comment]
Do we want to move this to https://github.com/opencost/opencost-helm-chart/ and maybe put it under `charts/opencost-parquet-exporter`? That would keep OpenCost Helm charts in 1 location. @lmello or @sntxrr want to weigh in?

**Comment by cklingspor** [comment]
> Do we want to move this to https://github.com/opencost/opencost-helm-chart/ and maybe put it under `charts/opencost-parquet-exporter`? That would keep OpenCost Helm charts in 1 location. @lmello or @sntxrr want to weigh in?

Sure thing. I did put it here because it was listed as a todo here. Therefore I assumed that it was meant to be here. But I can close here and move the code to https://github.com/opencost/opencost-helm-chart/

**Comment by mattray** [comment]
@cklingspor if you want to close this one and re-open it over in opencost-helm-charts that would be appreciated.

**Comment by cklingspor** [comment]
Continued here: https://github.com/opencost/opencost-helm-chart/pull/195

**Pull request closed without merging**
